import { logger } from '../lib/logger.js';
import { discordDispatcher } from './discordDispatcher.js';
import prisma from '../lib/prisma.js';
import { Resend } from 'resend';
import { config } from '../config.js';

const resend = new Resend(config.RESEND_API_KEY);
const FROM_EMAIL = config.RESEND_FROM_EMAIL;

export interface DispatchPayload {
    leadId: string;
    campaignId: string;
    userId: string;
    name: string;
    industry: string;
    painPoint: string;
    message: string;
    phone?: string | null;
    website?: string | null;
    location: string;
}

export class DispatchService {
    /**
     * Manual Dispatch: Triggered by user in UI
     * Sends email to lead (if available) + returns WhatsApp deep-link
     */
    async dispatchLead(leadId: string, userId: string) {
        try {
            const lead = await prisma.lead.findUnique({
                where: { id: leadId },
                include: { business: true, campaign: true }
            });

            if (!lead || lead.campaign.userId !== userId) {
                throw new Error('Lead not found or access denied');
            }

            const business = lead.business;
            let emailSent = false;

            // 1. Send Email to Lead if email exists
            if (business.email) {
                try {
                    await resend.emails.send({
                        from: FROM_EMAIL,
                        to: business.email,
                        subject: `Business Intelligence Report: ${business.name}`,
                        html: `
                            <div style="font-family: sans-serif; background-color: #ffffff; color: #050505; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 2px;">
                                <div style="background-color: #050505; padding: 20px; text-align: left; border-bottom: 2px solid #ff6d29;">
                                    <span style="color: #ffffff; font-size: 14px; font-weight: 900; letter-spacing: 0.2em; text-transform: uppercase;">HyprLead</span>
                                </div>
                                <div style="padding: 40px;">
                                    <h2 style="font-size: 18px; font-weight: 900; color: #050505; text-transform: uppercase; letter-spacing: -0.02em; margin-bottom: 24px;">Growth Intelligence</h2>
                                    <div style="font-size: 15px; line-height: 1.6; color: #4b5563; margin-bottom: 32px;">
                                        ${lead.suggestedMessage.replace(/\n/g, '<br>')}
                                    </div>
                                    <div style="border-top: 1px solid #f3f4f6; pt: 24px; font-size: 11px; color: #9ca3af; text-transform: uppercase; letter-spacing: 0.1em;">
                                        Generated by HyprLead Autonomous Engine
                                    </div>
                                </div>
                            </div>
                        `
                    });
                    emailSent = true;
                    logger.info(`[DISPATCH] Minimal email sent to lead: ${business.email}`);
                } catch (e: any) {
                    logger.error({ err: e.message }, 'Failed to send lead email');
                }
            }

            // 2. Generate Manual Outreach Links
            let whatsappUrl = null;
            let mailtoUrl = null;

            if (business.phone) {
                const cleanPhone = business.phone.replace(/\D/g, '');
                if (cleanPhone.length >= 7) {
                    whatsappUrl = `https://wa.me/${cleanPhone}?text=${encodeURIComponent(lead.suggestedMessage)}`;
                }
            }

            if (business.email) {
                const subject = encodeURIComponent(`Intelligence Report: ${business.name}`);
                const body = encodeURIComponent(lead.suggestedMessage);
                mailtoUrl = `mailto:${business.email}?subject=${subject}&body=${body}`;
            }

            // 3. Mark as Contacted
            await prisma.lead.update({
                where: { id: leadId },
                data: { status: 'CONTACTED', dispatchedAt: new Date() }
            });

            return { emailSent, whatsappUrl, mailtoUrl };
        } catch (error: any) {
            logger.error({ err: error.message }, 'Manual Dispatch Error');
            throw error;
        }
    }

    /**
     * Cycle Summary: Sent to the platform USER after every engine cycle
     */
    async sendUserCycleSummary(userId: string, sweepResults: { campaignName: string, count: number }[]) {
        try {
            const user = await prisma.user.findUnique({ where: { id: userId } });
            if (!user || !user.email) return;

            const totalFound = sweepResults.reduce((sum, r) => sum + r.count, 0);
            if (totalFound === 0) return;

            const campaignRows = sweepResults
                .map(r => `
                    <tr>
                        <td style="padding: 12px 0; border-bottom: 1px solid #1a1513; color: #a1a1aa; font-size: 13px;">${r.campaignName}</td>
                        <td style="padding: 12px 0; border-bottom: 1px solid #1a1513; color: #ff6d29; font-weight: 900; font-size: 13px; text-align: right;">${r.count} FOUND</td>
                    </tr>
                `)
                .join('');

            await resend.emails.send({
                from: FROM_EMAIL,
                to: user.email,
                subject: `CYCLE COMPLETE: ${totalFound} LEADS ACQUIRED`,
                html: `
                    <div style="font-family: sans-serif; background-color: #050505; color: #a1a1aa; max-width: 500px; margin: 0 auto; padding: 40px; border: 1px solid #1a1513; border-radius: 2px;">
                        <div style="margin-bottom: 40px;">
                            <span style="color: #ff6d29; font-size: 12px; font-weight: 900; letter-spacing: 0.3em; text-transform: uppercase;">HyprLead</span>
                            <h1 style="font-size: 24px; font-weight: 900; color: #ffffff; margin: 8px 0 0 0; letter-spacing: -0.04em; text-transform: uppercase;">Cycle Summary</h1>
                        </div>
                        
                        <div style="background-color: #1a1513; padding: 24px; border-radius: 2px; margin-bottom: 32px; border-left: 3px solid #ff6d29;">
                            <div style="font-size: 32px; font-weight: 900; color: #ffffff; line-height: 1;">${totalFound}</div>
                            <div style="font-size: 10px; font-weight: 900; color: #ff6d29; text-transform: uppercase; letter-spacing: 0.1em; margin-top: 4px;">Total Leads Found</div>
                        </div>

                        <table style="width: 100%; border-collapse: collapse;">
                            <thead>
                                <tr style="text-align: left; border-bottom: 1px solid #1a1513;">
                                    <th style="padding-bottom: 8px; font-size: 10px; font-weight: 900; color: #52525b; text-transform: uppercase; letter-spacing: 0.1em;">Campaign</th>
                                    <th style="padding-bottom: 8px; font-size: 10px; font-weight: 900; color: #52525b; text-transform: uppercase; letter-spacing: 0.1em; text-align: right;">Leads</th>
                                </tr>
                            </thead>
                            <tbody>
                                ${campaignRows}
                            </tbody>
                        </table>

                        <div style="margin-top: 40px;">
                            <a href="${process.env.FRONTEND_URL || 'http://localhost:3000'}/leads" 
                               style="background-color: #ff6d29; color: #ffffff; padding: 12px 24px; text-decoration: none; border-radius: 2px; font-size: 11px; font-weight: 900; text-transform: uppercase; letter-spacing: 0.1em; display: inline-block;">
                                View Dashboard
                            </a>
                        </div>
                        
                        <div style="margin-top: 40px; pt: 20px; border-top: 1px solid #1a1513;">
                            <p style="font-size: 10px; color: #52525b; margin: 0; text-transform: uppercase; letter-spacing: 0.05em;">Engine v2.4 // Autonomous Discovery</p>
                        </div>
                    </div>
                `
            });

            logger.info(`[SUMMARY] Minimal metrics sent to user: ${user.email}`);
        } catch (error: any) {
            logger.error({ err: error.message }, 'Cycle Summary Email Error');
        }
    }

    /**
     * Auto-dispatch to Discord (Legacy notification flow)
     */
    async notifyDiscord(payload: any) {
        const campaign = await prisma.campaign.findUnique({ where: { id: payload.campaignId } });
        if (campaign?.discordWebhook) {
            await discordDispatcher.dispatch(payload, 'warm', campaign.discordWebhook);
        }
    }
}

export const dispatchService = new DispatchService();
