import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { getAuthUser, authError } from '@/lib/api-auth';
import { Resend } from 'resend';
import { LeadStatus } from '@prisma/client';

const resend = new Resend(process.env.RESEND_API_KEY);
const FROM_EMAIL = process.env.RESEND_FROM_EMAIL || 'onboarding@resend.dev';

function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function cleanOutreachMessage(text: string) {
  let cleaned = (text || "")
    .replace(/<thought>[\s\S]*?<\/thought>/gi, "")
    .replace(/<thinking>[\s\S]*?<\/thinking>/gi, "")
    .replace(/```[\w-]*\n?/g, "")
    .replace(/<\/?email>/gi, "")
    .replace(/\*\*(Opening|The Hook\/Pain Point|The Solution|Call to Action|CTA|Subject):\*\*:?/gi, "")
    .replace(/^\s*[-*]\s+\*\*[^*\n]+:\*\*\s*/gm, "")
    .replace(/^\s*[-*]\s*(Opening|The Hook\/Pain Point|The Solution|Call to Action|CTA|Subject):\s*/gim, "")
    .replace(/^\s*`+\s*/gm, "")
    .replace(/\s*`+\s*$/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  const firstGreeting = cleaned.search(/\b(hi|hello|good day|hey|greetings)\b/i);
  if (firstGreeting > 0) cleaned = cleaned.slice(firstGreeting).trim();
  return cleaned;
}

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const user = await getAuthUser(req);
  if (!user) return authError();

  const { id } = await params;

  try {
    const body = await req.json().catch(() => ({}));
    const lead = await prisma.lead.findUnique({
      where: { id },
      include: { business: true, campaign: true }
    });

    if (!lead || lead.campaign.userId !== user.id) {
      return NextResponse.json({ error: 'Lead not found or access denied' }, { status: 404 });
    }

    const business = lead.business;
    const outreachMessage = cleanOutreachMessage(body.customMessage || lead.suggestedMessage);
    const escapedMessage = escapeHtml(outreachMessage).replace(/\n/g, '<br>');
    const escapedBusinessName = escapeHtml(business.name || 'there');
    let emailSent = false;

    // 1. Send Email to Lead if email exists
    if (business.email && process.env.RESEND_API_KEY) {
      try {
        await resend.emails.send({
          from: FROM_EMAIL,
          to: business.email,
          subject: `Business Intelligence Report: ${business.name}`,
          html: `
            <div style="font-family: sans-serif; background-color: #ffffff; color: #050505; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 2px;">
              <div style="background-color: #050505; padding: 20px; text-align: left; border-bottom: 2px solid #3b82f6;">
                <span style="color: #ffffff; font-size: 14px; font-weight: 900; letter-spacing: 0.2em; text-transform: uppercase;">HyprLead</span>
              </div>
              <div style="padding: 40px;">
                <h2 style="font-size: 18px; font-weight: 900; color: #050505; text-transform: uppercase; letter-spacing: -0.02em; margin-bottom: 24px;">Growth Intelligence</h2>
                <div style="font-size: 15px; line-height: 1.6; color: #4b5563; margin-bottom: 32px;">
                  ${escapedMessage}
                </div>
                <div style="border-top: 1px solid #f3f4f6; padding-top: 24px; font-size: 11px; color: #9ca3af; text-transform: uppercase; letter-spacing: 0.1em;">
                  Generated by HyprLead Autonomous Engine
                </div>
              </div>
            </div>
          `
        });
        emailSent = true;
      } catch (e: any) {
        console.error('Failed to send lead email:', e.message);
      }
    }

    // 2. Generate Manual Outreach Links
    let whatsappUrl = null;
    let mailtoUrl = null;
    let contactUrl = null;

    if (business.phone) {
      const cleanPhone = business.phone.replace(/\D/g, '');
      if (cleanPhone.length >= 7) {
        whatsappUrl = `https://wa.me/${cleanPhone}?text=${encodeURIComponent(outreachMessage)}`;
      }
    }

    if (business.email) {
      const subject = encodeURIComponent(`Intelligence Report: ${business.name}`);
      const body = encodeURIComponent(outreachMessage);
      mailtoUrl = `mailto:${business.email}?subject=${subject}&body=${body}`;
    }

    const contactPages = Array.isArray(business.contactPages) ? business.contactPages.filter(Boolean) : [];
    const socialProfiles = Array.isArray(business.socialProfiles) ? business.socialProfiles.filter(Boolean) : [];
    contactUrl = contactPages[0] || socialProfiles[0] || null;

    const hasDirectDispatch = emailSent || Boolean(body.markContacted);
    const hasOpenedRoute = Boolean(whatsappUrl || mailtoUrl || contactUrl);
    const status = hasDirectDispatch ? LeadStatus.CONTACTED : hasOpenedRoute ? LeadStatus.CONTACT_ROUTE_OPENED : lead.status;
    const dispatchedAt = hasDirectDispatch ? new Date() : lead.dispatchedAt;

    // 3. Track the strongest action we can honestly prove.
    await prisma.lead.update({
      where: { id },
      data: { status, dispatchedAt }
    });

    return NextResponse.json({ emailSent, whatsappUrl, mailtoUrl, contactUrl, status, businessName: escapedBusinessName });
  } catch (error) {
    console.error('API Error:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
