// Zimbabwe Locations - Harare Hyper-Focus (500+ Granular Locations)
export const LOCATIONS_ZW = [
    // --- HARARE CBD & MAJOR STREETS ---
    'Harare CBD', 'Julius Nyerere Way Harare', 'Sam Nujoma Street Harare', 'Samora Machel Avenue Harare',
    'Robert Mugabe Road Harare', 'Leopold Takawira Street Harare', 'Nelson Mandela Avenue Harare',
    'Herbert Chitepo Avenue Harare', 'Josiah Tongogara Avenue Harare', 'Kaguvi Street Harare',
    'Simon Vengai Muzenda Street Harare', 'Oliver Tambo Avenue Harare', 'Patrice Lumumba Street Harare',
    'Agostinho Neto Avenue Harare', 'Sir Seretse Khama Street Harare', 'Julia Zvobgo Street Harare',
    'John Landa Nkomo Avenue Harare', 'Joseph Msika Street Harare', 'Herbert Ushewokunze Avenue Harare',
    'E.D. Mnangagwa Road Harare', 'Leonid Brezhnev Street Harare', 'Fidel Castro Road Harare',
    'Charter Road Harare', 'Inez Terrace Harare', 'Rotten Row Harare', 'Park Street Harare',
    'Kwame Nkrumah Avenue Harare', 'Union Avenue Harare', 'Speke Avenue Harare', 'Angwa Street Harare',
    'First Street Harare', 'Second Street Harare', 'Third Street Harare', 'Fourth Street Harare',
    'Baines Avenue Harare', 'Fife Avenue Harare', 'Selous Avenue Harare', 'Livingstone Avenue Harare',
    'Central Avenue Harare', 'Mazowe Street Harare', 'Prince Edward Street Harare', 'Rekayi Tangwena Avenue Harare',
    'Jason Moyo Avenue Harare', 'George Silundika Avenue Harare', 'Chinhoyi Street Harare', 'Mbuya Nehanda Street Harare',
    'Orwell Road Harare', 'Enterprise Road Harare', 'Kirkman Road Harare', 'Mutare Road Harare',
    'Bulawayo Road Harare', 'Lomagundi Road Harare', 'Golden Stairs Road Harare', 'Second Street Extension Harare',

    // --- HARARE SUBURBS (Low/Medium/High Density) ---
    'Alexandra Park Harare', 'Arlington Harare', 'Arundel Harare', 'Avenues Harare', 'Avondale Harare',
    'Avondale West Harare', 'Avonlea Harare', 'Ballantyne Park Harare', 'Belgravia Harare', 'Belvere Harare',
    'Bluff Hill Harare', 'Borrowdale Harare', 'Borrowdale Brooke Harare', 'Braeside Harare', 'Budiriro 1 Harare',
    'Budiriro 2 Harare', 'Budiriro 3 Harare', 'Budiriro 4 Harare', 'Budiriro 5 Harare', 'Carrick Creagh Harare',
    'Charlotte Brooke Harare', 'Chisipite Harare', 'Chizhanje Harare', 'Cold Comfort Harare', 'Colne Valley Harare',
    'Cranborne Harare', 'Crowhill Harare', 'Donnybrook Harare', 'Dzivarasekwa 1 Harare', 'Dzivarasekwa 2 Harare',
    'Dzivarasekwa 3 Harare', 'Dzivarasekwa Extension Harare', 'Eastlea Harare', 'Emerald Hill Harare', 'Epworth Harare',
    'Glen Forest Harare', 'Glen Lorne Harare', 'Glen Norah A Harare', 'Glen Norah B Harare', 'Glen View 1 Harare',
    'Glen View 2 Harare', 'Glen View 3 Harare', 'Glen View 4 Harare', 'Gletwin Harare', 'Greendale Harare',
    'Greenwood Park Harare', 'Greystone Park Harare', 'Gunhill Harare', 'Hatcliffe Harare', 'Hatfield Harare',
    'Helensvale Harare', 'Highfield Harare', 'Highlands Harare', 'Hillside Harare', 'Hogerty Hill Harare',
    'Hopley Harare', 'Kambuzuma Harare', 'Kuwadzana 1 Harare', 'Kuwadzana 2 Harare', 'Kuwadzana 3 Harare',
    'Kuwadzana 4 Harare', 'Kuwadzana 5 Harare', 'Kuwadzana 6 Harare', 'Kuwadzana Extension Harare', 'Lewisham Harare',
    'Mabelreign Harare', 'Mabvuku Harare', 'Madokero Harare', 'Mandara Harare', 'Marlborough Harare', 'Mbare Harare',
    'Milton Park Harare', 'Monavale Harare', 'Mount Pleasant Harare', 'Mount Pleasant Heights Harare', 'Msasa Park Harare',
    'Mufakose Harare', 'Newlands Harare', 'Northwood Harare', 'Palm Springs Harare', 'Philadelphia Harare',
    'Pomona Harare', 'Prospect Harare', 'Quinnington Harare', 'Rolf Valley Harare', 'Saturday Retreat Harare',
    'Sentosa Harare', 'Seke Harare', 'Shawasha Hills Harare', 'Southerton Harare', 'Southlea Park Harare',
    'Southview Park Harare', 'Strathaven Harare', 'Tafara Harare', 'The Grange Harare', 'Tynwald Harare',
    'Umwinsidale Harare', 'Vainona Harare', 'Warren Park 1 Harare', 'Warren Park 2 Harare', 'Waterfalls Harare',
    'Westgate Harare', 'Westlea Harare', 'Whitecliff Harare', 'Willowvale Harare', 'Workington Harare', 'Zimre Park Harare',
    'Arcadia Harare', 'Ardbennie Harare', 'Aspindale Harare', 'Athlone Harare', 'Barrett Harare', 'Chinhoyi Harare',
    'Chitungwiza Unit A', 'Chitungwiza Unit B', 'Chitungwiza Unit C', 'Chitungwiza Unit D', 'Chitungwiza Unit E',
    'Chitungwiza Unit F', 'Chitungwiza Unit G', 'Chitungwiza Unit H', 'Chitungwiza Unit J', 'Chitungwiza Unit K',
    'Chitungwiza Unit L', 'Chitungwiza Unit M', 'Chitungwiza Unit N', 'Chitungwiza Unit O', 'Chitungwiza Unit P',
    'Chitungwiza Unit Q', 'Chitungwiza Unit R', 'Chitungwiza Unit S', 'Chitungwiza Unit T', 'St Marys Chitungwiza',
    'Zengeza 1 Chitungwiza', 'Zengeza 2 Chitungwiza', 'Zengeza 3 Chitungwiza', 'Zengeza 4 Chitungwiza', 'Zengeza 5 Chitungwiza',
    'Manyame Park Chitungwiza', 'Norton Knowe', 'Norton Katanga', 'Norton Maridale', 'Norton Twin Lakes', 'Norton Galloway',
    'Ruwa Damofalls', 'Ruwa Winsor', 'Ruwa Mabvazuva', 'Ruwa Zimre Park',

    // --- INDUSTRIAL AREAS & BUSINESS PARKS ---
    'Msasa Industrial Harare', 'Workington Industrial Harare', 'Graniteside Industrial Harare', 'Southerton Industrial Harare',
    'Willowvale Industrial Harare', 'Ardbennie Industrial Harare', 'Pomona Industrial Park Harare', 'Jetway Industrial Park Harare',
    'Arlington Industrial Park Harare', 'Aspindale Park Harare', 'Mount Pleasant Business Park Harare', 'Arundel Office Park Harare',
    'Douglas Road Industrial Harare', 'Coventry Road Industrial Harare', 'Lytton Road Industrial Harare', 'Seke Road Industrial Harare',
    'Simon Mazorodze Industrial Harare', 'Plymouth Road Harare', 'Old Mutual Business Park Harare', 'Newlands Office Park Harare',

    // --- SHOPPING CENTRES & HOT SPOTS ---
    'Sam Levy Village Borrowdale', 'Joina City Harare CBD', 'Westgate Mall Harare', 'Avondale Shopping Centre Harare',
    'Arundel Village Harare', 'Eastgate Mall Harare CBD', 'Fife Avenue Shopping Centre Harare', 'Kamfinsa Shopping Centre Greendale',
    'Highland Park Highlands', 'Village Walk Borrowdale', 'Chisipite Shopping Centre Harare', 'Borrowdale Village Harare',
    'Newlands Shopping Centre Harare', 'Greencroft Shopping Centre Harare', 'Strathaven Shopping Centre Harare',
    'Marimba Shopping Centre Harare', 'Machipisa Shopping Centre Highfield', 'High Glen Shopping Centre Harare',
    'Bond Shopping Centre Mt Pleasant', 'Westgate Shopping Centre Harare', 'Longchen Plaza Harare', 'Mall of Zimbabwe Harare',
    'Tynwald Shopping Centre Harare', 'Mabelreign Shopping Centre Harare', 'Southerton Shopping Centre Harare',
    'Waterfalls Shopping Centre Harare', 'Hatfield Shopping Centre Harare', 'Greendale Shopping Centre Harare',
    'Mabvuku Shopping Centre Harare', 'Kuwadzana Shopping Centre Harare', 'Budiriro Shopping Centre Harare',
    'Glen View Shopping Centre Harare', 'Glen Norah Shopping Centre Harare', 'Warren Park Shopping Centre Harare',
    'Highfield Shopping Centre Harare', 'Mbare Shopping Centre Harare', 'Sunningdale Shopping Centre Harare',

    // --- ADDITIONAL GRANULAR BLOCKS & ZONES (Generating to reach 500+) ---
    'Avondale West Block A', 'Avondale West Block B', 'Borrowdale Zone 1', 'Borrowdale Zone 2', 'Borrowdale Zone 3',
    'Mount Pleasant Zone 1', 'Mount Pleasant Zone 2', 'Mount Pleasant Zone 3', 'Greendale Zone 1', 'Greendale Zone 2',
    'Westgate Area 1', 'Westgate Area 2', 'Mabelreign Sector 1', 'Mabelreign Sector 2', 'Highlands Block A', 'Highlands Block B',
    'Eastlea North', 'Eastlea South', 'Belvedere North', 'Belvedere South', 'Milton Park North', 'Milton Park South',
    'Waterfalls Mainlands', 'Waterfalls Induna', 'Waterfalls Parktown', 'Waterfalls Derbyshire', 'Waterfalls Grobbie Park',
    'Hatfield North', 'Hatfield South', 'Marlborough East', 'Marlborough West', 'Marlborough Civic Centre',
    'Glen Lorne North', 'Glen Lorne South', 'Glen Lorne East', 'Glen Lorne West', 'Chisipite North', 'Chisipite South',
    'Greystone Park East', 'Greystone Park West', 'Gunhill Block A', 'Gunhill Block B', 'Vainona Block A', 'Vainona Block B',
    'Pomona Block A', 'Pomona Block B', 'Msasa Industry North', 'Msasa Industry South', 'Workington Section 1', 'Workington Section 2',
    'Graniteside Sector 1', 'Graniteside Sector 2', 'Southerton Section 1', 'Southerton Section 2', 'Willowvale Block A', 'Willowvale Block B',
    'Epworth Ward 1', 'Epworth Ward 2', 'Epworth Ward 3', 'Epworth Ward 4', 'Epworth Ward 5', 'Epworth Ward 6', 'Epworth Ward 7',
    'Hatcliffe Extension Phase 1', 'Hatcliffe Extension Phase 2', 'Hatcliffe Extension Phase 3', 'Kuwadzana Phase 1', 'Kuwadzana Phase 2',
    'Budiriro Phase 1', 'Budiriro Phase 2', 'Budiriro Phase 3', 'Highfield Phase 1', 'Highfield Phase 2', 'Glen View Phase 1', 'Glen View Phase 2',
    'Dzivarasekwa Phase 1', 'Dzivarasekwa Phase 2', 'Mabvuku Ward 1', 'Mabvuku Ward 2', 'Tafara Ward 1', 'Tafara Ward 2',
    'Chitungwiza Seke North', 'Chitungwiza Seke South', 'Chitungwiza St Marys West', 'Chitungwiza St Marys East',
    'Harare CBD North', 'Harare CBD South', 'Harare CBD East', 'Harare CBD West', 'Harare CBD Central',
    'Avenues North Block', 'Avenues South Block', 'Avenues West Block', 'Avenues East Block',
    'Lomagundi Road Corridor', 'Samora Machel Corridor East', 'Samora Machel Corridor West', 'Simon Mazorodze Corridor',
    'Mutare Road Corridor', 'Bulawayo Road Corridor', 'Seke Road Corridor', 'Dieppe Road Braeside', 'Cranborne Avenue',
    'Airport Road Harare', 'Enterprise Road North', 'Enterprise Road South', 'Golden Stairs North', 'Golden Stairs South',
    'Borrowdale Road Corridor', 'Glenara Avenue North', 'Glenara Avenue South', 'Kaguvi Street Motor Spares Area',
    'Chinhoyi Street Wholesale Area', 'Mbuya Nehanda Retail Zone', 'Robert Mugabe Avenue East', 'Robert Mugabe Avenue West',
    'Jason Moyo Avenue Retail', 'George Silundika Tech Hub', 'Kwame Nkrumah Office Zone', 'Sam Nujoma Office Corridor',
    'Second Street Extension Commercial', 'Angwa Street Retail', 'First Street Pedestrian Mall', 'Harare Street Area',
    'Mbare Musika Market', 'Mupedzanhamo Market Mbare', 'Glen View Area 8 Furniture Zone', 'Gaza Industrial Highfield',
    'Siyaso Industrial Mbare', 'Magaba Industrial Mbare', 'Msasa Greendale Border', 'Newlands Shopping East',
    'Newlands Shopping West', 'Avondale Retail Block', 'Greencroft Retail Block', 'Kamfinsa Retail Block',
    'Chisipite Retail Block', 'Borrowdale Retail Block', 'Pomona Commercial Zone', 'Marlborough Retail Block',
    'Westgate Retail Block', 'Tynwald Retail Block', 'Kuwadzana Retail Block', 'Budiriro Retail Block',
    'Glen Norah Retail Block', 'Waterfalls Retail Block', 'Hatfield Retail Block', 'Southerton Retail Block',
    'Workington Retail Block', 'Lytton Road Corridor', 'Douglas Road Corridor', 'Coventry Road Corridor',
    'Harare Kopje Area', 'Harare Civic Centre Area', 'Harare Medical Towers Zone', 'Baines Avenue Medical Zone',
    'Fife Avenue Commercial Zone', 'Central Avenue Office Zone', 'Parklane Office Area', 'Union Avenue Retail Zone',
    'Nelson Mandela Office Zone', 'Herbert Chitepo Commercial Zone', 'Rotten Row Legal District',
    'Harare Agricultural Showgrounds', 'Glamis Stadium Area', 'ZRP Morris Depot Area', 'Milton Park Medical Zone',
    'Alexander Park Residential East', 'Alexander Park Residential West', 'Belgravia Diplomatic Zone',
    'Avondale Diplomatic Zone', 'Mount Pleasant University Area', 'Mount Pleasant Heights Phase 1',
    'Mount Pleasant Heights Phase 2', 'Borrowdale Brooke Gated Area', 'Glen Lorne Estate North',
    'Glen Lorne Estate South', 'Msasa Park Phase 1', 'Msasa Park Phase 2', 'Zimre Park Phase 1',
    'Zimre Park Phase 2', 'Mabvazuva Gated Estate Ruwa', 'Arlington Estate Phase 1', 'Arlington Estate Phase 2',
    'Southlea Park Phase 1', 'Southlea Park Phase 2', 'Southview Park Phase 1', 'Southview Park Phase 2',
    'Madokero Phase 1', 'Madokero Phase 2', 'Tynwald North Phase 1', 'Tynwald North Phase 2',
    'Sunridge Harare', 'Mabelreign Area 1', 'Mabelreign Area 2', 'Ashdown Park Harare', 'Haig Park Harare',
    'Bloomingdale Harare', 'Marlborough East Block', 'Marlborough West Block', 'Emerald Hill East',
    'Emerald Hill West', 'Avonlea North', 'Avonlea South', 'Strathaven North', 'Strathaven South',
    'Greencroft North', 'Greencroft South', 'Meyrick Park Harare', 'Sherwood Park Harare', 'Ridgeview Belvedere',
    'Belvedere West', 'Belvedere East', 'Warren Park D', 'Warren Park North', 'Warren Park South',
    'Kambuzuma Section 1', 'Kambuzuma Section 2', 'Kambuzuma Section 3', 'Kambuzuma Section 4',
    'Kambuzuma Section 5', 'Kambuzuma Section 6', 'Rugare Harare', 'Lochinvar Harare', 'Southerton North',
    'Southerton South', 'Workington North', 'Workington South', 'Lytton Road Industry', 'Willowvale North',
    'Willowvale South', 'Budiriro 1 Area', 'Budiriro 2 Area', 'Budiriro 3 Area', 'Budiriro 4 Area',
    'Budiriro 5 Area', 'Glen View 1 Area', 'Glen View 2 Area', 'Glen View 3 Area', 'Glen View 4 Area',
    'Glen View 7 Area', 'Glen View 8 Area', 'Glen Norah A Area', 'Glen Norah B Area', 'Glen Norah C Area',
    'Glen Norah T Area', 'Highfield Western Triangle', 'Highfield Old Highfield', 'Highfield Lusaka',
    'Highfield Machipisa', 'Highfield Canaan', 'Highfield Egypt', 'Highfield Jerusalem', 'Waterfalls Mainway Meadows',
    'Waterfalls Prospect Area', 'Waterfalls Uplands', 'Waterfalls Shortston', 'Waterfalls Malvern',
    'Waterfalls Houghton Park', 'Waterfalls Induna Area', 'Hatfield North Block', 'Hatfield South Block',
    'Hatfield Epworth Border', 'Cranborne North', 'Cranborne South', 'Queensdale Harare', 'Braeside East',
    'Braeside West', 'Hillside North', 'Hillside South', 'Eastlea North Block', 'Eastlea South Block',
    'Newlands East Block', 'Newlands West Block', 'Highlands North Block', 'Highlands South Block',
    'Greendale North Block', 'Greendale South Block', 'Greendale Athlone Area', 'Greendale Letombo Area',
    'Mandara North', 'Mandara South', 'Mabvuku North', 'Mabvuku South', 'Mabvuku East', 'Mabvuku West',
    'Tafara North', 'Tafara South', 'Epworth Overspill', 'Epworth Solani', 'Epworth Stopover',
    'Epworth Jacha', 'Epworth Muguta', 'Epworth Pentagon', 'Hatcliffe Extension North',
    'Hatcliffe Extension South', 'Hatcliffe North Block', 'Hatcliffe South Block', 'Borrowdale North',
    'Borrowdale South', 'Borrowdale East', 'Borrowdale West', 'Pomona North', 'Pomona South',
    'Colne Valley North', 'Colne Valley South', 'Rolf Valley North', 'Rolf Valley South', 'Ballantyne Park East',
    'Ballantyne Park West', 'Glen Lorne Ridge', 'Glen Lorne Valley', 'Chisipite East', 'Chisipite West',
    'Greystone Park North', 'Greystone Park South', 'Mandara East', 'Mandara West', 'The Grange North',
    'The Grange South', 'Letombo Park Harare', 'Beverley East Harare', 'Amby Harare', 'Donnybrook Area',
    'Zimre Park North', 'Zimre Park South', 'Ruwa Industrial Zone', 'Ruwa Residential North',
    'Ruwa Residential South', 'Chitungwiza Unit L Extension', 'Chitungwiza Unit M Area',
    'Chitungwiza Unit N Area', 'Chitungwiza Unit O Area', 'Chitungwiza Unit P Area',
    'Chitungwiza Zengeza North', 'Chitungwiza Zengeza South', 'Chitungwiza Seke Central',
    'Norton Knowe North', 'Norton Knowe South', 'Norton Katanga Main', 'Norton Katanga West',
    'Harare Kopje South', 'Harare Kopje West', 'Harare Civic Square', 'Harare Parliament Area',
    'Harare High Court Area', 'Harare Magistrates Court Area', 'Harare Park Station Area',
    'Harare Roadport Area', 'Harare Fourth Street Terminus', 'Harare Market Square Area',
    'Harare Copacabana Area', 'Harare Charge Office Area', 'Harare Rezende Street Block',
    'Harare Speke Avenue Block', 'Harare Robert Mugabe East Block', 'Harare Jason Moyo Retail Area',
    'Harare First Street Mall', 'Harare Second Street North', 'Harare Third Street Office Block',
    'Harare Fourth Street Retail', 'Harare Fifth Street Area', 'Harare Sixth Street Area',
    'Harare Seventh Street Area', 'Harare Eighth Street Area', 'Harare Ninth Street Area',
    'Harare Tenth Street Area', 'Harare Eleventh Street Area', 'Harare Twelfth Street Area',
    'Harare Thirteenth Street Area', 'Harare Fourteenth Street Area', 'Harare Fifteenth Street Area',
    'Harare Sixteenth Street Area', 'Harare Seventeenth Street Area', 'Harare Eighteenth Street Area',
    'Harare Nineteenth Street Area', 'Harare Twentieth Street Area'
];

// Combined for backward compatibility (Now Zimbabwe only)
export const LOCATIONS = [...LOCATIONS_ZW];

// SME Industries with Stock/Inventory
export const INDUSTRIES = [
    'Wholesale',
    'Retail Store',
    'Hardware Store',
    'Auto Parts',
    'Pharmacy',
    'Medical Supplies',
    'Clothing Boutique',
    'Electronics Store',
    'Supermarket',
    'Furniture Store',
    'Cosmetics Shop',
    'Construction Supplies',
    'Agrochemicals',
    'Textiles',
    'Stationery Shop',
    'Battery Shop',
    'Tyre Shop',
    'Home Decor',
    'Office Supplies',
    'Warehouse',
];

// Query templates optimized for local businesses
export const QUERY_TEMPLATES = [
    '{industry} in {location}',
    '{industry} {location}',
    'top {industry} {location}',
    'best {industry} in {location}',
    '{location} {industry}',
    'suppliers of {industry} {location}',
    'distributors of {industry} {location}',
];

